apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
    spec:
      containers:
      - name: add-task
        image: practice30.azurecr.io/addtask:v3
        ports:
        - containerPort: 8000
